"""
Command Allowlisting (Feature #52)

Intercepts shell and terminal commands generated by the agent.
Blocks destructive operations by default while allowing typical development and
exploration commands.

This implements a default-deny philosophy for known dangerous commands.
"""

import re
from typing import List, Tuple
from observability import get_logging_system

class CommandBlockException(PermissionError):
    pass

class CommandAllowlist:
    """
    Evaluates terminal commands before execution.
    Maintains a list of explicitly forbidden tokens and regex patterns.
    """
    
    # Tokens that are immediately blocked if found anywhere in the command
    FORBIDDEN_TOKENS = {
        "rm -rf", "mkfs", "dd ", "> /dev/sda", "format", 
        "del /f /s /q", "rmdir /s /q", "rd /s /q",
        "wget -O -", "curl | bash"
    }

    # Regex patterns for more complex blocking
    # E.g., deleting root or user directories, wiping disks
    FORBIDDEN_PATTERNS = [
        re.compile(r"rm\s+-[rRf]+\s+/(?!\S)"),        # rm -rf /
        re.compile(r"rm\s+-[rRf]+\s+~/?(?!\S)"),      # rm -rf ~
        re.compile(r"del\s+.*C:\\Windows", re.I),     # Windows wipe
        re.compile(r"mkfs\.(ext|vfat|ntfs|xfs)"),     # Format disk
    ]

    # Commands that are always safe and skip deeper inspection
    SAFE_PREFIXES = {
        "ls", "cat", "echo", "pwd", "whoami", "git status", "git diff",
        "dir", "type", "cd", "python --version", "node -v", "npm -v", "pip list"
    }

    def __init__(self):
        self.logger = get_logging_system()

    def check_command(self, command: str) -> Tuple[bool, str]:
        """
        Evaluate a command string.
        Returns: (is_allowed: bool, reason: str)
        """
        cmd_stripped = command.strip()
        
        # 1. Check safe prefixes for fast-path approval
        for safe in self.SAFE_PREFIXES:
            if cmd_stripped.startswith(safe + " ") or cmd_stripped == safe:
                return True, "matches_safe_prefix"

        # 2. Check forbidden explicit tokens
        cmd_lower = cmd_stripped.lower()
        for token in self.FORBIDDEN_TOKENS:
            if token in cmd_lower:
                self.logger.warning(f"CommandBlocked: Matched forbidden token '{token}' in '{command}'")
                return False, f"Contains forbidden command token: '{token}'"

        # 3. Check regex patterns
        for pattern in self.FORBIDDEN_PATTERNS:
            if pattern.search(cmd_stripped):
                self.logger.warning(f"CommandBlocked: Matched forbidden pattern '{pattern.pattern}' in '{command}'")
                return False, f"Matches forbidden pattern: {pattern.pattern}"

        # 4. Default Allow (assuming the agent is operating under HIL approval system)
        # The HIL system will catch any dangerous tools. This allowlist is a defense-in-depth layer.
        return True, "passed_heuristics"

    def enforce(self, command: str):
        """
        Evaluate command and raise CommandBlockException if forbidden.
        """
        is_allowed, reason = self.check_command(command)
        if not is_allowed:
            raise CommandBlockException(f"Command execution blocked by security policy. Reason: {reason}")
